$outputFile = "CurveUpEndDataIndex.asm"

# Clear or create file with header comment
" ; CurveUpEndDataIndex generated by script" | Out-File -Encoding ascii $outputFile

for ($i = 59; $i -ge 1; $i--) {
    $j = $i - 1
    foreach ($page in 0, 1) {
        foreach ($region in "TOP", "BOTTOM") {
            $block = "BlockCurveUpEndPage${page}${region}from${i}to${j}"
            $changed = "CurveUpEndPage${page}${region}ChangedPixelsfrom${i}to${j}"
            $addr = "CurveUpEndPage${page}${region}Addressesfrom${i}to${j}"
            $instr = "CurveUpEndPage${page}${region}WriteInstructionsfrom${i}to${j}"
            # Final flag formula
            if ($region -eq "TOP") {
                $flag = $page * 2
            } else {
                $flag = $page * 2 + 1
            }

            $line = "db $block, $flag | dw $changed, $addr, $instr"
            Add-Content -Path $outputFile -Encoding ascii -Value $line
        }
    }
}
