$outputFile = "CurveLeftDataIndex.asm"

# Clear or create file with header comment
" ; CurveLeftDataIndex generated by script" | Out-File -Encoding ascii $outputFile

for ($i = 0; $i -lt 75; $i++) {
    $j = $i + 1
    foreach ($page in 0, 1) {
        foreach ($region in "TOP", "BOTTOM") {
            $block = "BlockCurveLeftPage${page}${region}from${i}to${j}"
            $changed = "CurveLeftPage${page}${region}ChangedPixelsfrom${i}to${j}"
            $addr = "CurveLeftPage${page}${region}Addressesfrom${i}to${j}"
            $instr = "CurveLeftPage${page}${region}WriteInstructionsfrom${i}to${j}"

            # Final flag formula
            if ($region -eq "TOP") {
                $flag = $page * 2
            } else {
                $flag = $page * 2 + 1
            }

            $line = "db $block, $flag | dw $changed, $addr, $instr"

            # Prefix with ; if it's a TOP line
            if ($region -eq "TOP") {
                $line = "; " + $line
            }

            Add-Content -Path $outputFile -Encoding ascii -Value $line
        }
    }
}
