$outputFile = "CurveDownDataIndex.asm"

# Clear or create file with header comment
" ; CurveDownDataIndex generated by script" | Out-File -Encoding ascii $outputFile

for ($i = 0; $i -le 59-1; $i++) {
    $j = $i + 1
    foreach ($page in 0, 1) {
        foreach ($region in "TOP", "BOTTOM") {
            $block = "BlockCurveDownPage${page}${region}from${i}to${j}"
            $changed = "CurveDownPage${page}${region}ChangedPixelsfrom${i}to${j}"
            $addr = "CurveDownPage${page}${region}Addressesfrom${i}to${j}"
            $instr = "CurveDownPage${page}${region}WriteInstructionsfrom${i}to${j}"
            # Final flag formula
            if ($region -eq "TOP") {
                $flag = $page * 2
            } else {
                $flag = $page * 2 + 1
            }

            $line = "db $block, $flag | dw $changed, $addr, $instr"
            Add-Content -Path $outputFile -Encoding ascii -Value $line
        }
    }
}
