$outputFile = "CurveLeftDataIndex.asm"

# Clear or create file with header comment
" ; CurveLeftDataIndex generated by script" | Out-File -Encoding ascii $outputFile

for ($i = 0; $i -le 75-1; $i++) {
    $j = $i + 1
    foreach ($page in 0, 1) {
        foreach ($region in "TOP", "BOTTOM") {
            $block = "BlockCurveLeftPage${page}${region}from${i}to${j}"
            $changed = "CurveLeftPage${page}${region}ChangedPixelsfrom${i}to${j}"
            $addr = "CurveLeftPage${page}${region}Addressesfrom${i}to${j}"
            $instr = "CurveLeftPage${page}${region}WriteInstructionsfrom${i}to${j}"
            $flag = if ($region -eq "TOP") { 0 } else { 1 }

            $line = "db $block, $flag | dw $changed, $addr, $instr"
            Add-Content -Path $outputFile -Encoding ascii -Value $line
        }
    }
}
