$outputFile = "CurveLeftEndDataIndex.asm"

# Clear or create file with header comment
" ; CurveLeftEndDataIndex generated by script" | Out-File -Encoding ascii $outputFile

for ($i = 75; $i -ge 1; $i--) {
    $j = $i - 1
    foreach ($page in 0, 1) {
        foreach ($region in "TOP", "BOTTOM") {
            $block = "BlockCurveLeftEndPage${page}${region}from${i}to${j}"
            $changed = "CurveLeftEndPage${page}${region}ChangedPixelsfrom${i}to${j}"
            $addr = "CurveLeftEndPage${page}${region}Addressesfrom${i}to${j}"
            $instr = "CurveLeftEndPage${page}${region}WriteInstructionsfrom${i}to${j}"

            # Final flag formula
            if ($region -eq "TOP") {
                $flag = $page * 2
            } else {
                $flag = $page * 2 + 1
            }

            $line = "db $block, $flag | dw $changed, $addr, $instr"

            # Comment out if region is TOP
            if ($region -eq "TOP") {
                $line = "; " + $line
            }

            Add-Content -Path $outputFile -Encoding ascii -Value $line
        }
    }
}
