# Output file name
$outputFile = "PerspectiveYTable.asm"

# Header comment
"; Perspective Y table generated by PowerShell script" | Out-File -Encoding ascii $outputFile

# Loop over z from 0 to 21831 in steps of 50
for ($z = 0; $z -le 21831; $z += 50) {
    $y = [math]::Floor(588842 / ($z + 3727) + 50)
    if ($y -ge 73) {
        "db $y" | Add-Content -Encoding ascii -Path $outputFile
    }
}

Write-Host "File '$outputFile' generated successfully."