# Output file name
$outputFile = "PerspectiveYTable.asm"

# Header comment
"; Perspective Y table generated by PowerShell script" | Out-File -Encoding ascii $outputFile

# Loop over z from 0 to 15000 in steps of 100
for ($z = 0; $z -le 15000; $z += 100) {
    $y = [math]::Floor(588842 / ($z + 5305) + 50)
    "db $y" | Add-Content -Encoding ascii -Path $outputFile
}

Write-Host "File '$outputFile' generated successfully."
