
; db BlockCurveRightEndPage0TOPfrom37to36, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom37to36, CurveRightEndPage0TOPAddressesfrom37to36, CurveRightEndPage0TOPWriteInstructionsfrom37to36
db BlockCurveRightEndPage0BOTTOMfrom37to36, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom37to36, CurveRightEndPage0BOTTOMAddressesfrom37to36, CurveRightEndPage0BOTTOMWriteInstructionsfrom37to36
; db BlockCurveRightEndPage1TOPfrom37to36, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom37to36, CurveRightEndPage1TOPAddressesfrom37to36, CurveRightEndPage1TOPWriteInstructionsfrom37to36
db BlockCurveRightEndPage1BOTTOMfrom37to36, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom37to36, CurveRightEndPage1BOTTOMAddressesfrom37to36, CurveRightEndPage1BOTTOMWriteInstructionsfrom37to36
; db BlockCurveRightEndPage0TOPfrom36to35, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom36to35, CurveRightEndPage0TOPAddressesfrom36to35, CurveRightEndPage0TOPWriteInstructionsfrom36to35
db BlockCurveRightEndPage0BOTTOMfrom36to35, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom36to35, CurveRightEndPage0BOTTOMAddressesfrom36to35, CurveRightEndPage0BOTTOMWriteInstructionsfrom36to35
; db BlockCurveRightEndPage1TOPfrom36to35, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom36to35, CurveRightEndPage1TOPAddressesfrom36to35, CurveRightEndPage1TOPWriteInstructionsfrom36to35
db BlockCurveRightEndPage1BOTTOMfrom36to35, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom36to35, CurveRightEndPage1BOTTOMAddressesfrom36to35, CurveRightEndPage1BOTTOMWriteInstructionsfrom36to35
; db BlockCurveRightEndPage0TOPfrom35to34, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom35to34, CurveRightEndPage0TOPAddressesfrom35to34, CurveRightEndPage0TOPWriteInstructionsfrom35to34
db BlockCurveRightEndPage0BOTTOMfrom35to34, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom35to34, CurveRightEndPage0BOTTOMAddressesfrom35to34, CurveRightEndPage0BOTTOMWriteInstructionsfrom35to34
; db BlockCurveRightEndPage1TOPfrom35to34, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom35to34, CurveRightEndPage1TOPAddressesfrom35to34, CurveRightEndPage1TOPWriteInstructionsfrom35to34
db BlockCurveRightEndPage1BOTTOMfrom35to34, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom35to34, CurveRightEndPage1BOTTOMAddressesfrom35to34, CurveRightEndPage1BOTTOMWriteInstructionsfrom35to34
; db BlockCurveRightEndPage0TOPfrom34to33, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom34to33, CurveRightEndPage0TOPAddressesfrom34to33, CurveRightEndPage0TOPWriteInstructionsfrom34to33
db BlockCurveRightEndPage0BOTTOMfrom34to33, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom34to33, CurveRightEndPage0BOTTOMAddressesfrom34to33, CurveRightEndPage0BOTTOMWriteInstructionsfrom34to33
; db BlockCurveRightEndPage1TOPfrom34to33, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom34to33, CurveRightEndPage1TOPAddressesfrom34to33, CurveRightEndPage1TOPWriteInstructionsfrom34to33
db BlockCurveRightEndPage1BOTTOMfrom34to33, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom34to33, CurveRightEndPage1BOTTOMAddressesfrom34to33, CurveRightEndPage1BOTTOMWriteInstructionsfrom34to33
; db BlockCurveRightEndPage0TOPfrom33to32, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom33to32, CurveRightEndPage0TOPAddressesfrom33to32, CurveRightEndPage0TOPWriteInstructionsfrom33to32
db BlockCurveRightEndPage0BOTTOMfrom33to32, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom33to32, CurveRightEndPage0BOTTOMAddressesfrom33to32, CurveRightEndPage0BOTTOMWriteInstructionsfrom33to32
; db BlockCurveRightEndPage1TOPfrom33to32, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom33to32, CurveRightEndPage1TOPAddressesfrom33to32, CurveRightEndPage1TOPWriteInstructionsfrom33to32
db BlockCurveRightEndPage1BOTTOMfrom33to32, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom33to32, CurveRightEndPage1BOTTOMAddressesfrom33to32, CurveRightEndPage1BOTTOMWriteInstructionsfrom33to32
; db BlockCurveRightEndPage0TOPfrom32to31, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom32to31, CurveRightEndPage0TOPAddressesfrom32to31, CurveRightEndPage0TOPWriteInstructionsfrom32to31
db BlockCurveRightEndPage0BOTTOMfrom32to31, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom32to31, CurveRightEndPage0BOTTOMAddressesfrom32to31, CurveRightEndPage0BOTTOMWriteInstructionsfrom32to31
; db BlockCurveRightEndPage1TOPfrom32to31, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom32to31, CurveRightEndPage1TOPAddressesfrom32to31, CurveRightEndPage1TOPWriteInstructionsfrom32to31
db BlockCurveRightEndPage1BOTTOMfrom32to31, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom32to31, CurveRightEndPage1BOTTOMAddressesfrom32to31, CurveRightEndPage1BOTTOMWriteInstructionsfrom32to31
; db BlockCurveRightEndPage0TOPfrom31to30, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom31to30, CurveRightEndPage0TOPAddressesfrom31to30, CurveRightEndPage0TOPWriteInstructionsfrom31to30
db BlockCurveRightEndPage0BOTTOMfrom31to30, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom31to30, CurveRightEndPage0BOTTOMAddressesfrom31to30, CurveRightEndPage0BOTTOMWriteInstructionsfrom31to30
; db BlockCurveRightEndPage1TOPfrom31to30, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom31to30, CurveRightEndPage1TOPAddressesfrom31to30, CurveRightEndPage1TOPWriteInstructionsfrom31to30
db BlockCurveRightEndPage1BOTTOMfrom31to30, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom31to30, CurveRightEndPage1BOTTOMAddressesfrom31to30, CurveRightEndPage1BOTTOMWriteInstructionsfrom31to30
; db BlockCurveRightEndPage0TOPfrom30to29, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom30to29, CurveRightEndPage0TOPAddressesfrom30to29, CurveRightEndPage0TOPWriteInstructionsfrom30to29
db BlockCurveRightEndPage0BOTTOMfrom30to29, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom30to29, CurveRightEndPage0BOTTOMAddressesfrom30to29, CurveRightEndPage0BOTTOMWriteInstructionsfrom30to29
; db BlockCurveRightEndPage1TOPfrom30to29, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom30to29, CurveRightEndPage1TOPAddressesfrom30to29, CurveRightEndPage1TOPWriteInstructionsfrom30to29
db BlockCurveRightEndPage1BOTTOMfrom30to29, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom30to29, CurveRightEndPage1BOTTOMAddressesfrom30to29, CurveRightEndPage1BOTTOMWriteInstructionsfrom30to29
; db BlockCurveRightEndPage0TOPfrom29to28, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom29to28, CurveRightEndPage0TOPAddressesfrom29to28, CurveRightEndPage0TOPWriteInstructionsfrom29to28
db BlockCurveRightEndPage0BOTTOMfrom29to28, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom29to28, CurveRightEndPage0BOTTOMAddressesfrom29to28, CurveRightEndPage0BOTTOMWriteInstructionsfrom29to28
; db BlockCurveRightEndPage1TOPfrom29to28, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom29to28, CurveRightEndPage1TOPAddressesfrom29to28, CurveRightEndPage1TOPWriteInstructionsfrom29to28
db BlockCurveRightEndPage1BOTTOMfrom29to28, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom29to28, CurveRightEndPage1BOTTOMAddressesfrom29to28, CurveRightEndPage1BOTTOMWriteInstructionsfrom29to28
; db BlockCurveRightEndPage0TOPfrom28to27, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom28to27, CurveRightEndPage0TOPAddressesfrom28to27, CurveRightEndPage0TOPWriteInstructionsfrom28to27
db BlockCurveRightEndPage0BOTTOMfrom28to27, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom28to27, CurveRightEndPage0BOTTOMAddressesfrom28to27, CurveRightEndPage0BOTTOMWriteInstructionsfrom28to27
; db BlockCurveRightEndPage1TOPfrom28to27, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom28to27, CurveRightEndPage1TOPAddressesfrom28to27, CurveRightEndPage1TOPWriteInstructionsfrom28to27
db BlockCurveRightEndPage1BOTTOMfrom28to27, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom28to27, CurveRightEndPage1BOTTOMAddressesfrom28to27, CurveRightEndPage1BOTTOMWriteInstructionsfrom28to27
; db BlockCurveRightEndPage0TOPfrom27to26, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom27to26, CurveRightEndPage0TOPAddressesfrom27to26, CurveRightEndPage0TOPWriteInstructionsfrom27to26
db BlockCurveRightEndPage0BOTTOMfrom27to26, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom27to26, CurveRightEndPage0BOTTOMAddressesfrom27to26, CurveRightEndPage0BOTTOMWriteInstructionsfrom27to26
; db BlockCurveRightEndPage1TOPfrom27to26, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom27to26, CurveRightEndPage1TOPAddressesfrom27to26, CurveRightEndPage1TOPWriteInstructionsfrom27to26
db BlockCurveRightEndPage1BOTTOMfrom27to26, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom27to26, CurveRightEndPage1BOTTOMAddressesfrom27to26, CurveRightEndPage1BOTTOMWriteInstructionsfrom27to26
; db BlockCurveRightEndPage0TOPfrom26to25, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom26to25, CurveRightEndPage0TOPAddressesfrom26to25, CurveRightEndPage0TOPWriteInstructionsfrom26to25
db BlockCurveRightEndPage0BOTTOMfrom26to25, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom26to25, CurveRightEndPage0BOTTOMAddressesfrom26to25, CurveRightEndPage0BOTTOMWriteInstructionsfrom26to25
; db BlockCurveRightEndPage1TOPfrom26to25, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom26to25, CurveRightEndPage1TOPAddressesfrom26to25, CurveRightEndPage1TOPWriteInstructionsfrom26to25
db BlockCurveRightEndPage1BOTTOMfrom26to25, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom26to25, CurveRightEndPage1BOTTOMAddressesfrom26to25, CurveRightEndPage1BOTTOMWriteInstructionsfrom26to25
; db BlockCurveRightEndPage0TOPfrom25to24, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom25to24, CurveRightEndPage0TOPAddressesfrom25to24, CurveRightEndPage0TOPWriteInstructionsfrom25to24
db BlockCurveRightEndPage0BOTTOMfrom25to24, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom25to24, CurveRightEndPage0BOTTOMAddressesfrom25to24, CurveRightEndPage0BOTTOMWriteInstructionsfrom25to24
; db BlockCurveRightEndPage1TOPfrom25to24, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom25to24, CurveRightEndPage1TOPAddressesfrom25to24, CurveRightEndPage1TOPWriteInstructionsfrom25to24
db BlockCurveRightEndPage1BOTTOMfrom25to24, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom25to24, CurveRightEndPage1BOTTOMAddressesfrom25to24, CurveRightEndPage1BOTTOMWriteInstructionsfrom25to24
; db BlockCurveRightEndPage0TOPfrom24to23, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom24to23, CurveRightEndPage0TOPAddressesfrom24to23, CurveRightEndPage0TOPWriteInstructionsfrom24to23
db BlockCurveRightEndPage0BOTTOMfrom24to23, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom24to23, CurveRightEndPage0BOTTOMAddressesfrom24to23, CurveRightEndPage0BOTTOMWriteInstructionsfrom24to23
; db BlockCurveRightEndPage1TOPfrom24to23, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom24to23, CurveRightEndPage1TOPAddressesfrom24to23, CurveRightEndPage1TOPWriteInstructionsfrom24to23
db BlockCurveRightEndPage1BOTTOMfrom24to23, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom24to23, CurveRightEndPage1BOTTOMAddressesfrom24to23, CurveRightEndPage1BOTTOMWriteInstructionsfrom24to23
; db BlockCurveRightEndPage0TOPfrom23to22, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom23to22, CurveRightEndPage0TOPAddressesfrom23to22, CurveRightEndPage0TOPWriteInstructionsfrom23to22
db BlockCurveRightEndPage0BOTTOMfrom23to22, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom23to22, CurveRightEndPage0BOTTOMAddressesfrom23to22, CurveRightEndPage0BOTTOMWriteInstructionsfrom23to22
; db BlockCurveRightEndPage1TOPfrom23to22, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom23to22, CurveRightEndPage1TOPAddressesfrom23to22, CurveRightEndPage1TOPWriteInstructionsfrom23to22
db BlockCurveRightEndPage1BOTTOMfrom23to22, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom23to22, CurveRightEndPage1BOTTOMAddressesfrom23to22, CurveRightEndPage1BOTTOMWriteInstructionsfrom23to22
; db BlockCurveRightEndPage0TOPfrom22to21, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom22to21, CurveRightEndPage0TOPAddressesfrom22to21, CurveRightEndPage0TOPWriteInstructionsfrom22to21
db BlockCurveRightEndPage0BOTTOMfrom22to21, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom22to21, CurveRightEndPage0BOTTOMAddressesfrom22to21, CurveRightEndPage0BOTTOMWriteInstructionsfrom22to21
; db BlockCurveRightEndPage1TOPfrom22to21, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom22to21, CurveRightEndPage1TOPAddressesfrom22to21, CurveRightEndPage1TOPWriteInstructionsfrom22to21
db BlockCurveRightEndPage1BOTTOMfrom22to21, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom22to21, CurveRightEndPage1BOTTOMAddressesfrom22to21, CurveRightEndPage1BOTTOMWriteInstructionsfrom22to21
; db BlockCurveRightEndPage0TOPfrom21to20, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom21to20, CurveRightEndPage0TOPAddressesfrom21to20, CurveRightEndPage0TOPWriteInstructionsfrom21to20
db BlockCurveRightEndPage0BOTTOMfrom21to20, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom21to20, CurveRightEndPage0BOTTOMAddressesfrom21to20, CurveRightEndPage0BOTTOMWriteInstructionsfrom21to20
; db BlockCurveRightEndPage1TOPfrom21to20, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom21to20, CurveRightEndPage1TOPAddressesfrom21to20, CurveRightEndPage1TOPWriteInstructionsfrom21to20
db BlockCurveRightEndPage1BOTTOMfrom21to20, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom21to20, CurveRightEndPage1BOTTOMAddressesfrom21to20, CurveRightEndPage1BOTTOMWriteInstructionsfrom21to20
; db BlockCurveRightEndPage0TOPfrom20to19, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom20to19, CurveRightEndPage0TOPAddressesfrom20to19, CurveRightEndPage0TOPWriteInstructionsfrom20to19
db BlockCurveRightEndPage0BOTTOMfrom20to19, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom20to19, CurveRightEndPage0BOTTOMAddressesfrom20to19, CurveRightEndPage0BOTTOMWriteInstructionsfrom20to19
; db BlockCurveRightEndPage1TOPfrom20to19, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom20to19, CurveRightEndPage1TOPAddressesfrom20to19, CurveRightEndPage1TOPWriteInstructionsfrom20to19
db BlockCurveRightEndPage1BOTTOMfrom20to19, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom20to19, CurveRightEndPage1BOTTOMAddressesfrom20to19, CurveRightEndPage1BOTTOMWriteInstructionsfrom20to19
; db BlockCurveRightEndPage0TOPfrom19to18, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom19to18, CurveRightEndPage0TOPAddressesfrom19to18, CurveRightEndPage0TOPWriteInstructionsfrom19to18
db BlockCurveRightEndPage0BOTTOMfrom19to18, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom19to18, CurveRightEndPage0BOTTOMAddressesfrom19to18, CurveRightEndPage0BOTTOMWriteInstructionsfrom19to18
; db BlockCurveRightEndPage1TOPfrom19to18, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom19to18, CurveRightEndPage1TOPAddressesfrom19to18, CurveRightEndPage1TOPWriteInstructionsfrom19to18
db BlockCurveRightEndPage1BOTTOMfrom19to18, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom19to18, CurveRightEndPage1BOTTOMAddressesfrom19to18, CurveRightEndPage1BOTTOMWriteInstructionsfrom19to18
; db BlockCurveRightEndPage0TOPfrom18to17, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom18to17, CurveRightEndPage0TOPAddressesfrom18to17, CurveRightEndPage0TOPWriteInstructionsfrom18to17
db BlockCurveRightEndPage0BOTTOMfrom18to17, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom18to17, CurveRightEndPage0BOTTOMAddressesfrom18to17, CurveRightEndPage0BOTTOMWriteInstructionsfrom18to17
; db BlockCurveRightEndPage1TOPfrom18to17, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom18to17, CurveRightEndPage1TOPAddressesfrom18to17, CurveRightEndPage1TOPWriteInstructionsfrom18to17
db BlockCurveRightEndPage1BOTTOMfrom18to17, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom18to17, CurveRightEndPage1BOTTOMAddressesfrom18to17, CurveRightEndPage1BOTTOMWriteInstructionsfrom18to17
; db BlockCurveRightEndPage0TOPfrom17to16, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom17to16, CurveRightEndPage0TOPAddressesfrom17to16, CurveRightEndPage0TOPWriteInstructionsfrom17to16
db BlockCurveRightEndPage0BOTTOMfrom17to16, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom17to16, CurveRightEndPage0BOTTOMAddressesfrom17to16, CurveRightEndPage0BOTTOMWriteInstructionsfrom17to16
; db BlockCurveRightEndPage1TOPfrom17to16, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom17to16, CurveRightEndPage1TOPAddressesfrom17to16, CurveRightEndPage1TOPWriteInstructionsfrom17to16
db BlockCurveRightEndPage1BOTTOMfrom17to16, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom17to16, CurveRightEndPage1BOTTOMAddressesfrom17to16, CurveRightEndPage1BOTTOMWriteInstructionsfrom17to16
; db BlockCurveRightEndPage0TOPfrom16to15, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom16to15, CurveRightEndPage0TOPAddressesfrom16to15, CurveRightEndPage0TOPWriteInstructionsfrom16to15
db BlockCurveRightEndPage0BOTTOMfrom16to15, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom16to15, CurveRightEndPage0BOTTOMAddressesfrom16to15, CurveRightEndPage0BOTTOMWriteInstructionsfrom16to15
; db BlockCurveRightEndPage1TOPfrom16to15, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom16to15, CurveRightEndPage1TOPAddressesfrom16to15, CurveRightEndPage1TOPWriteInstructionsfrom16to15
db BlockCurveRightEndPage1BOTTOMfrom16to15, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom16to15, CurveRightEndPage1BOTTOMAddressesfrom16to15, CurveRightEndPage1BOTTOMWriteInstructionsfrom16to15
; db BlockCurveRightEndPage0TOPfrom15to14, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom15to14, CurveRightEndPage0TOPAddressesfrom15to14, CurveRightEndPage0TOPWriteInstructionsfrom15to14
db BlockCurveRightEndPage0BOTTOMfrom15to14, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom15to14, CurveRightEndPage0BOTTOMAddressesfrom15to14, CurveRightEndPage0BOTTOMWriteInstructionsfrom15to14
; db BlockCurveRightEndPage1TOPfrom15to14, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom15to14, CurveRightEndPage1TOPAddressesfrom15to14, CurveRightEndPage1TOPWriteInstructionsfrom15to14
db BlockCurveRightEndPage1BOTTOMfrom15to14, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom15to14, CurveRightEndPage1BOTTOMAddressesfrom15to14, CurveRightEndPage1BOTTOMWriteInstructionsfrom15to14
; db BlockCurveRightEndPage0TOPfrom14to13, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom14to13, CurveRightEndPage0TOPAddressesfrom14to13, CurveRightEndPage0TOPWriteInstructionsfrom14to13
db BlockCurveRightEndPage0BOTTOMfrom14to13, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom14to13, CurveRightEndPage0BOTTOMAddressesfrom14to13, CurveRightEndPage0BOTTOMWriteInstructionsfrom14to13
; db BlockCurveRightEndPage1TOPfrom14to13, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom14to13, CurveRightEndPage1TOPAddressesfrom14to13, CurveRightEndPage1TOPWriteInstructionsfrom14to13
db BlockCurveRightEndPage1BOTTOMfrom14to13, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom14to13, CurveRightEndPage1BOTTOMAddressesfrom14to13, CurveRightEndPage1BOTTOMWriteInstructionsfrom14to13
; db BlockCurveRightEndPage0TOPfrom13to12, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom13to12, CurveRightEndPage0TOPAddressesfrom13to12, CurveRightEndPage0TOPWriteInstructionsfrom13to12
db BlockCurveRightEndPage0BOTTOMfrom13to12, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom13to12, CurveRightEndPage0BOTTOMAddressesfrom13to12, CurveRightEndPage0BOTTOMWriteInstructionsfrom13to12
; db BlockCurveRightEndPage1TOPfrom13to12, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom13to12, CurveRightEndPage1TOPAddressesfrom13to12, CurveRightEndPage1TOPWriteInstructionsfrom13to12
db BlockCurveRightEndPage1BOTTOMfrom13to12, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom13to12, CurveRightEndPage1BOTTOMAddressesfrom13to12, CurveRightEndPage1BOTTOMWriteInstructionsfrom13to12
; db BlockCurveRightEndPage0TOPfrom12to11, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom12to11, CurveRightEndPage0TOPAddressesfrom12to11, CurveRightEndPage0TOPWriteInstructionsfrom12to11
db BlockCurveRightEndPage0BOTTOMfrom12to11, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom12to11, CurveRightEndPage0BOTTOMAddressesfrom12to11, CurveRightEndPage0BOTTOMWriteInstructionsfrom12to11
; db BlockCurveRightEndPage1TOPfrom12to11, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom12to11, CurveRightEndPage1TOPAddressesfrom12to11, CurveRightEndPage1TOPWriteInstructionsfrom12to11
db BlockCurveRightEndPage1BOTTOMfrom12to11, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom12to11, CurveRightEndPage1BOTTOMAddressesfrom12to11, CurveRightEndPage1BOTTOMWriteInstructionsfrom12to11
; db BlockCurveRightEndPage0TOPfrom11to10, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom11to10, CurveRightEndPage0TOPAddressesfrom11to10, CurveRightEndPage0TOPWriteInstructionsfrom11to10
db BlockCurveRightEndPage0BOTTOMfrom11to10, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom11to10, CurveRightEndPage0BOTTOMAddressesfrom11to10, CurveRightEndPage0BOTTOMWriteInstructionsfrom11to10
; db BlockCurveRightEndPage1TOPfrom11to10, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom11to10, CurveRightEndPage1TOPAddressesfrom11to10, CurveRightEndPage1TOPWriteInstructionsfrom11to10
db BlockCurveRightEndPage1BOTTOMfrom11to10, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom11to10, CurveRightEndPage1BOTTOMAddressesfrom11to10, CurveRightEndPage1BOTTOMWriteInstructionsfrom11to10
; db BlockCurveRightEndPage0TOPfrom10to9, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom10to9, CurveRightEndPage0TOPAddressesfrom10to9, CurveRightEndPage0TOPWriteInstructionsfrom10to9
db BlockCurveRightEndPage0BOTTOMfrom10to9, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom10to9, CurveRightEndPage0BOTTOMAddressesfrom10to9, CurveRightEndPage0BOTTOMWriteInstructionsfrom10to9
; db BlockCurveRightEndPage1TOPfrom10to9, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom10to9, CurveRightEndPage1TOPAddressesfrom10to9, CurveRightEndPage1TOPWriteInstructionsfrom10to9
db BlockCurveRightEndPage1BOTTOMfrom10to9, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom10to9, CurveRightEndPage1BOTTOMAddressesfrom10to9, CurveRightEndPage1BOTTOMWriteInstructionsfrom10to9
; db BlockCurveRightEndPage0TOPfrom9to8, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom9to8, CurveRightEndPage0TOPAddressesfrom9to8, CurveRightEndPage0TOPWriteInstructionsfrom9to8
db BlockCurveRightEndPage0BOTTOMfrom9to8, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom9to8, CurveRightEndPage0BOTTOMAddressesfrom9to8, CurveRightEndPage0BOTTOMWriteInstructionsfrom9to8
; db BlockCurveRightEndPage1TOPfrom9to8, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom9to8, CurveRightEndPage1TOPAddressesfrom9to8, CurveRightEndPage1TOPWriteInstructionsfrom9to8
db BlockCurveRightEndPage1BOTTOMfrom9to8, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom9to8, CurveRightEndPage1BOTTOMAddressesfrom9to8, CurveRightEndPage1BOTTOMWriteInstructionsfrom9to8
; db BlockCurveRightEndPage0TOPfrom8to7, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom8to7, CurveRightEndPage0TOPAddressesfrom8to7, CurveRightEndPage0TOPWriteInstructionsfrom8to7
db BlockCurveRightEndPage0BOTTOMfrom8to7, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom8to7, CurveRightEndPage0BOTTOMAddressesfrom8to7, CurveRightEndPage0BOTTOMWriteInstructionsfrom8to7
; db BlockCurveRightEndPage1TOPfrom8to7, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom8to7, CurveRightEndPage1TOPAddressesfrom8to7, CurveRightEndPage1TOPWriteInstructionsfrom8to7
db BlockCurveRightEndPage1BOTTOMfrom8to7, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom8to7, CurveRightEndPage1BOTTOMAddressesfrom8to7, CurveRightEndPage1BOTTOMWriteInstructionsfrom8to7
; db BlockCurveRightEndPage0TOPfrom7to6, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom7to6, CurveRightEndPage0TOPAddressesfrom7to6, CurveRightEndPage0TOPWriteInstructionsfrom7to6
db BlockCurveRightEndPage0BOTTOMfrom7to6, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom7to6, CurveRightEndPage0BOTTOMAddressesfrom7to6, CurveRightEndPage0BOTTOMWriteInstructionsfrom7to6
; db BlockCurveRightEndPage1TOPfrom7to6, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom7to6, CurveRightEndPage1TOPAddressesfrom7to6, CurveRightEndPage1TOPWriteInstructionsfrom7to6
db BlockCurveRightEndPage1BOTTOMfrom7to6, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom7to6, CurveRightEndPage1BOTTOMAddressesfrom7to6, CurveRightEndPage1BOTTOMWriteInstructionsfrom7to6
; db BlockCurveRightEndPage0TOPfrom6to5, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom6to5, CurveRightEndPage0TOPAddressesfrom6to5, CurveRightEndPage0TOPWriteInstructionsfrom6to5
db BlockCurveRightEndPage0BOTTOMfrom6to5, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom6to5, CurveRightEndPage0BOTTOMAddressesfrom6to5, CurveRightEndPage0BOTTOMWriteInstructionsfrom6to5
; db BlockCurveRightEndPage1TOPfrom6to5, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom6to5, CurveRightEndPage1TOPAddressesfrom6to5, CurveRightEndPage1TOPWriteInstructionsfrom6to5
db BlockCurveRightEndPage1BOTTOMfrom6to5, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom6to5, CurveRightEndPage1BOTTOMAddressesfrom6to5, CurveRightEndPage1BOTTOMWriteInstructionsfrom6to5
; db BlockCurveRightEndPage0TOPfrom5to4, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom5to4, CurveRightEndPage0TOPAddressesfrom5to4, CurveRightEndPage0TOPWriteInstructionsfrom5to4
db BlockCurveRightEndPage0BOTTOMfrom5to4, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom5to4, CurveRightEndPage0BOTTOMAddressesfrom5to4, CurveRightEndPage0BOTTOMWriteInstructionsfrom5to4
; db BlockCurveRightEndPage1TOPfrom5to4, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom5to4, CurveRightEndPage1TOPAddressesfrom5to4, CurveRightEndPage1TOPWriteInstructionsfrom5to4
db BlockCurveRightEndPage1BOTTOMfrom5to4, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom5to4, CurveRightEndPage1BOTTOMAddressesfrom5to4, CurveRightEndPage1BOTTOMWriteInstructionsfrom5to4
; db BlockCurveRightEndPage0TOPfrom4to3, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom4to3, CurveRightEndPage0TOPAddressesfrom4to3, CurveRightEndPage0TOPWriteInstructionsfrom4to3
db BlockCurveRightEndPage0BOTTOMfrom4to3, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom4to3, CurveRightEndPage0BOTTOMAddressesfrom4to3, CurveRightEndPage0BOTTOMWriteInstructionsfrom4to3
; db BlockCurveRightEndPage1TOPfrom4to3, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom4to3, CurveRightEndPage1TOPAddressesfrom4to3, CurveRightEndPage1TOPWriteInstructionsfrom4to3
db BlockCurveRightEndPage1BOTTOMfrom4to3, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom4to3, CurveRightEndPage1BOTTOMAddressesfrom4to3, CurveRightEndPage1BOTTOMWriteInstructionsfrom4to3
; db BlockCurveRightEndPage0TOPfrom3to2, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom3to2, CurveRightEndPage0TOPAddressesfrom3to2, CurveRightEndPage0TOPWriteInstructionsfrom3to2
db BlockCurveRightEndPage0BOTTOMfrom3to2, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom3to2, CurveRightEndPage0BOTTOMAddressesfrom3to2, CurveRightEndPage0BOTTOMWriteInstructionsfrom3to2
; db BlockCurveRightEndPage1TOPfrom3to2, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom3to2, CurveRightEndPage1TOPAddressesfrom3to2, CurveRightEndPage1TOPWriteInstructionsfrom3to2
db BlockCurveRightEndPage1BOTTOMfrom3to2, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom3to2, CurveRightEndPage1BOTTOMAddressesfrom3to2, CurveRightEndPage1BOTTOMWriteInstructionsfrom3to2
; db BlockCurveRightEndPage0TOPfrom2to1, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom2to1, CurveRightEndPage0TOPAddressesfrom2to1, CurveRightEndPage0TOPWriteInstructionsfrom2to1
db BlockCurveRightEndPage0BOTTOMfrom2to1, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom2to1, CurveRightEndPage0BOTTOMAddressesfrom2to1, CurveRightEndPage0BOTTOMWriteInstructionsfrom2to1
; db BlockCurveRightEndPage1TOPfrom2to1, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom2to1, CurveRightEndPage1TOPAddressesfrom2to1, CurveRightEndPage1TOPWriteInstructionsfrom2to1
db BlockCurveRightEndPage1BOTTOMfrom2to1, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom2to1, CurveRightEndPage1BOTTOMAddressesfrom2to1, CurveRightEndPage1BOTTOMWriteInstructionsfrom2to1
; db BlockCurveRightEndPage0TOPfrom1to0, 0 | dw CurveRightEndPage0TOPChangedPixelsfrom1to0, CurveRightEndPage0TOPAddressesfrom1to0, CurveRightEndPage0TOPWriteInstructionsfrom1to0
db BlockCurveRightEndPage0BOTTOMfrom1to0, 1 | dw CurveRightEndPage0BOTTOMChangedPixelsfrom1to0, CurveRightEndPage0BOTTOMAddressesfrom1to0, CurveRightEndPage0BOTTOMWriteInstructionsfrom1to0
; db BlockCurveRightEndPage1TOPfrom1to0, 2 | dw CurveRightEndPage1TOPChangedPixelsfrom1to0, CurveRightEndPage1TOPAddressesfrom1to0, CurveRightEndPage1TOPWriteInstructionsfrom1to0
db BlockCurveRightEndPage1BOTTOMfrom1to0, 3 | dw CurveRightEndPage1BOTTOMChangedPixelsfrom1to0, CurveRightEndPage1BOTTOMAddressesfrom1to0, CurveRightEndPage1BOTTOMWriteInstructionsfrom1to0
